
services:
  test-runner:
    image: test-runner:latest
    container_name: test-runner-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    network_mode: "host"
    command: "pytest -s --html=report.html"
