# .github/workflows/ci.yml
name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/iam/iam" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests and Generate Reports
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        pytest -s --html=report.html
      continue-on-error: true

    - name: Create "public" folder and move files
      run: |
        mkdir -p public
        mkdir -p public/assets
        mv report.html public/index.html
        mv assets/style.css public/assets/

    - name: Deploy To Github Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public


  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t test-runner:latest .

    - name: Run Docker Container
      run: |
        mkdir -p public2
        mkdir -p public2/assets
        docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --network="host" --name=runner test-runner
        docker wait runner
        docker cp runner:/app/report.html public2/index.html2
        docker cp runner:/app/assets/style.css public2/assets/style.css
        echo "Files copied"

    - name: List Current Directory and Files
      run: |
        echo "Current working directory:"
        pwd
        echo "Listing all files and directories:"
        ls -al

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: |
          public2/report.html
          public2/assets/style.css
