# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/iam/iam" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests and Generate Reports
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        pytest pytest -s --html=report.html
      continue-on-error: true

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: report.html
        path: report.html

#  docker:
#    name: Build Docker Image
#    runs-on: ubuntu-latest
#    needs: test
#
#    steps:
#    - name: Checkout Repository
#      uses: actions/checkout@v3
#
#    - name: Log in to Docker Hub
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#
#    - name: Build Docker Image
#      run: |
#        docker build -t your-image-name:latest .
#        docker tag your-image-name:latest your-dockerhub-repo/your-image-name:latest
#
#    - name: Push Docker Image
#      run: |
#        docker push your-dockerhub-repo/your-image-name:latest
